# Generated by Django 5.0.6 on 2024-07-18 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0002_remove_comments_comment_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
