# Generated by Django 5.0.6 on 2024-07-21 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0003_comments_comment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "type_of_notification",
                    models.CharField(
                        choices=[
                            ("started_following", "New Follower"),
                            ("like_post", "New Post like"),
                            ("comment", "new Comment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_created_by",
                        to="secondary.profile",
                    ),
                ),
                (
                    "notification_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_create_for",
                        to="secondary.profile",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secondary.post",
                    ),
                ),
            ],
        ),
    ]
