# Generated by Django 5.0.6 on 2024-07-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0004_alter_followers_id_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="secondary.comments",
            ),
        ),
    ]
