# Generated by Django 5.0.6 on 2024-07-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0005_comments_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="secondary.comments",
            ),
        ),
    ]
