# Generated by Django 5.0.6 on 2024-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0006_alter_comments_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="type_of_notification",
            field=models.CharField(
                choices=[
                    ("started_following", "New Follower"),
                    ("like_post", "New Post like"),
                    ("comment", "New Comment"),
                    ("replied", "Replied"),
                ],
                max_length=50,
            ),
        ),
    ]
