# Generated by Django 5.0.6 on 2024-07-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0007_alter_notifications_type_of_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="secondary.comments",
            ),
        ),
    ]
