# Generated by Django 5.0.6 on 2024-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0008_notifications_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
