# Generated by Django 5.0.6 on 2024-07-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0009_profile_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentLoves",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("react_time", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_lover",
                        to="secondary.comments",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secondary.profile",
                    ),
                ),
            ],
        ),
    ]
