# Generated by Django 5.0.6 on 2024-07-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0010_commentloves"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="comment_like",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Comment_like",
                to="secondary.comments",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comment",
                to="secondary.comments",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="type_of_notification",
            field=models.CharField(
                choices=[
                    ("started_following", "New Follower"),
                    ("like_post", "New Post like"),
                    ("comment", "New Comment"),
                    ("replied", "Replied"),
                    ("like_comment", "New Comment Like"),
                ],
                max_length=50,
            ),
        ),
    ]
