# Generated by Django 5.0.6 on 2024-07-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0011_notifications_comment_like_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message_body", models.CharField(max_length=500)),
                ("message_time", models.DateTimeField(auto_now_add=True)),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reciever",
                        to="secondary.profile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sender",
                        to="secondary.profile",
                    ),
                ),
            ],
        ),
    ]
