# Generated by Django 5.0.6 on 2024-07-26 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0012_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="message_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="messages",
            name="message_time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
