# Generated by Django 5.0.6 on 2024-07-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0013_messages_message_date_alter_messages_message_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="seen",
            field=models.BooleanField(default=True),
        ),
    ]
