# Generated by Django 5.0.6 on 2024-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0014_messages_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message_body", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
