# Generated by Django 5.0.6 on 2024-07-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0016_helpmessage_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetVerified",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("account_type", models.CharField(max_length=100)),
                ("profile_image", models.ImageField(upload_to="request_images")),
                ("desc", models.TextField()),
                ("social_link1", models.TextField()),
                ("social_link2", models.TextField()),
                ("social_link3", models.TextField()),
                ("additional_notes", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
