# Generated by Django 5.0.6 on 2024-07-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0017_getverified"),
    ]

    operations = [
        migrations.AddField(
            model_name="getverified",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="secondary.profile",
            ),
            preserve_default=False,
        ),
    ]
