# Generated by Django 5.0.6 on 2024-07-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondary", "0018_getverified_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getverified",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="request_images"),
        ),
    ]
